---
  header_logo_url: http://Mantodea.archive.speciesfile.org/HomePage/Mantodea/img_Logo/SiteLogo.jpg
  header_logo_text: My project
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
