---
  project_name: "Mantodea Species File"
  project_citation: "Mantodea Species File"
  project_authors: "Spearman L, Stiewe MBD, Otte D, Eades D"
  project_url: "https://Mantodea.speciesfile.org"
  project_old_url: "http://Mantodea.archive.speciesfile.org" 
  focal_taxon: "Mantodea"
  focal_taxon_common_name: "praying mantids"
  contact_email: "m.stiewe@nhm.ac.uk"
